import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import {withProductSite} from '@beyond10x/docs-system/product-site';

// This runs in Node.js. The product layer (landing page, tokens, components, code themes) is the
// one `withProductSite` call at the bottom; everything under `docs/reference/` is generated by the
// `commission-docs` crate from the ESS specification.

const config: Config = {
  title: 'Commission',
  tagline: 'Build agents you can give responsibility to.',
  favicon: 'img/mark.svg',

  future: {
    v4: true,
  },

  // Published at https://beyond10x.github.io/commission/
  url: 'https://beyond10x.github.io',
  baseUrl: '/commission/',

  organizationName: 'beyond10x',
  projectName: 'commission',
  trailingSlash: false,

  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',

  markdown: {
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
    mermaid: true,
  },

  themes: ['@docusaurus/theme-mermaid'],

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: 'docs',
          editUrl: 'https://github.com/beyond10x/commission/tree/main/website/',
        },
        blog: false,
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    navbar: {
      title: 'Commission',
      items: [
        {to: '/docs/', label: 'Documentation', position: 'left'},
        {to: '/docs/reference/domain-model', label: 'Domain model', position: 'left'},
        {to: '/docs/status', label: 'Status', position: 'left'},
        {href: 'https://github.com/beyond10x/commission', label: 'GitHub', position: 'right'},
      ],
    },
    footer: {
      links: [
        {
          title: 'Documentation',
          items: [
            {label: 'What Commission is', to: '/docs/'},
            {label: 'A run', to: '/docs/concepts/a-run'},
            {label: 'Domain model', to: '/docs/reference/domain-model'},
          ],
        },
        {
          title: 'Project',
          items: [
            {label: 'Status', to: '/docs/status'},
            {label: 'Source', href: 'https://github.com/beyond10x/commission'},
          ],
        },
      ],
      copyright: 'A beyond10x project. Commission · Apache-2.0.',
    },
  } satisfies Preset.ThemeConfig,
};

export default withProductSite(config, {landing: './product.json', product: 'commission'});
